CHAPTERS = [
    # Class 4
    {"name": "Shapes and Sizes", "slug": "shapes-sizes-4", "class_num": 4},
    {"name": "Place Value", "slug": "place-value-4", "class_num": 4},
    {"name": "Addition and Subtraction", "slug": "add-subtract-4", "class_num": 4},
    {"name": "Multiplication", "slug": "multiplication-4", "class_num": 4},
    {"name": "Division", "slug": "division-4", "class_num": 4},
    {"name": "Factors and Multiples", "slug": "factors-multiples-4", "class_num": 4},
    {"name": "Fractions", "slug": "fractions-4", "class_num": 4},
    {"name": "Decimals", "slug": "decimals-4", "class_num": 4},
    {"name": "Money", "slug": "money-4", "class_num": 4},
    {"name": "Time", "slug": "time-4", "class_num": 4},
    {"name": "Measurement", "slug": "measurement-4", "class_num": 4},
    {"name": "Perimeter and Area", "slug": "perimeter-area-4", "class_num": 4},
    {"name": "Patterns", "slug": "patterns-4", "class_num": 4},
    {"name": "Data Handling", "slug": "data-handling-4", "class_num": 4},
    # Class 5
    {"name": "The Fish Tale", "slug": "fish-tale-5", "class_num": 5},
    {"name": "Shapes and Angles", "slug": "shapes-angles-5", "class_num": 5},
    {"name": "How Many Squares?", "slug": "how-many-squares-5", "class_num": 5},
    {"name": "Parts and Wholes", "slug": "parts-wholes-5", "class_num": 5},
    {"name": "Does it Look the Same?", "slug": "look-same-5", "class_num": 5},
    {"name": "Be My Multiple", "slug": "be-my-multiple-5", "class_num": 5},
    {"name": "Can You Create It?", "slug": "create-it-5", "class_num": 5},
    {"name": "Mapping Your Way", "slug": "mapping-way-5", "class_num": 5},
    {"name": "Boxes and Puzzles", "slug": "boxes-puzzles-5", "class_num": 5},
    {"name": "Tenths and Hundredths", "slug": "tenths-hundredths-5", "class_num": 5},
    {"name": "Area and its Boundary", "slug": "area-boundary-5", "class_num": 5},
    {"name": "Smart Charts", "slug": "smart-charts-5", "class_num": 5},
    {"name": "Ways to Multiply", "slug": "ways-multiply-5", "class_num": 5},
    {"name": "Ways to Divide", "slug": "ways-divide-5", "class_num": 5},
    {"name": "How Big? How Heavy?", "slug": "big-heavy-5", "class_num": 5},
    # Class 6
    {"name": "Knowing Our Numbers", "slug": "knowing-numbers-6", "class_num": 6},
    {"name": "Whole Numbers", "slug": "whole-numbers-6", "class_num": 6},
    {"name": "Playing with Numbers", "slug": "playing-numbers-6", "class_num": 6},
    {"name": "Basic Geometrical Ideas", "slug": "basic-geometry-6", "class_num": 6},
    {
        "name": "Understanding Elementary Shapes",
        "slug": "elementary-shapes-6",
        "class_num": 6,
    },
    {"name": "Integers", "slug": "integers-6", "class_num": 6},
    {"name": "Fractions", "slug": "fractions-6", "class_num": 6},
    {"name": "Decimals", "slug": "decimals-6", "class_num": 6},
    {"name": "Data Handling", "slug": "data-handling-6", "class_num": 6},
    {"name": "Mensuration", "slug": "mensuration-6", "class_num": 6},
    {"name": "Algebra", "slug": "algebra-6", "class_num": 6},
    {"name": "Ratio and Proportion", "slug": "ratio-proportion-6", "class_num": 6},
    {"name": "Symmetry", "slug": "symmetry-6", "class_num": 6},
    {"name": "Practical Geometry", "slug": "practical-geometry-6", "class_num": 6},
    # Class 7
    {"name": "Integers", "slug": "integers-7", "class_num": 7},
    {"name": "Fractions and Decimals", "slug": "fractions-decimals-7", "class_num": 7},
    {"name": "Data Handling", "slug": "data-handling-7", "class_num": 7},
    {"name": "Simple Equations", "slug": "simple-equations-7", "class_num": 7},
    {"name": "Lines and Angles", "slug": "lines-angles-7", "class_num": 7},
    {
        "name": "The Triangle and its Properties",
        "slug": "triangle-properties-7",
        "class_num": 7,
    },
    {
        "name": "Congruence of Triangles",
        "slug": "congruence-triangles-7",
        "class_num": 7,
    },
    {"name": "Comparing Quantities", "slug": "comparing-quantities-7", "class_num": 7},
    {"name": "Rational Numbers", "slug": "rational-numbers-7", "class_num": 7},
    {"name": "Practical Geometry", "slug": "practical-geometry-7", "class_num": 7},
    {"name": "Perimeter and Area", "slug": "perimeter-area-7", "class_num": 7},
    {
        "name": "Algebraic Expressions",
        "slug": "algebraic-expressions-7",
        "class_num": 7,
    },
    {"name": "Exponents and Powers", "slug": "exponents-powers-7", "class_num": 7},
    {"name": "Symmetry", "slug": "symmetry-7", "class_num": 7},
    {"name": "Visualising Solid Shapes", "slug": "solid-shapes-7", "class_num": 7},
    # Class 10
    {"name": "Real Numbers", "slug": "real-numbers", "class_num": 10},
    {"name": "Polynomials", "slug": "polynomials", "class_num": 10},
    {"name": "Pair of Linear Equations", "slug": "linear-equations", "class_num": 10},
    {"name": "Quadratic Equations", "slug": "quadratic-equations", "class_num": 10},
    {
        "name": "Arithmetic Progressions",
        "slug": "arithmetic-progressions",
        "class_num": 10,
    },
    {"name": "Triangles", "slug": "triangles", "class_num": 10},
    {"name": "Coordinate Geometry", "slug": "coordinate-geometry", "class_num": 10},
    {"name": "Introduction to Trigonometry", "slug": "trigonometry", "class_num": 10},
    {
        "name": "Applications of Trigonometry",
        "slug": "trigonometry-applications",
        "class_num": 10,
    },
    {"name": "Circles", "slug": "circles", "class_num": 10},
    {"name": "Areas Related to Circles", "slug": "areas-circles", "class_num": 10},
    {
        "name": "Surface Areas and Volumes",
        "slug": "surface-areas-volumes",
        "class_num": 10,
    },
    {"name": "Statistics", "slug": "statistics", "class_num": 10},
    {"name": "Probability", "slug": "probability", "class_num": 10},
    # Class 11
    {"name": "Sets", "slug": "sets", "class_num": 11},
    {"name": "Relations and Functions", "slug": "relations-functions", "class_num": 11},
    {"name": "Trigonometric Functions", "slug": "trig-functions", "class_num": 11},
    {"name": "Complex Numbers", "slug": "complex-numbers", "class_num": 11},
    {"name": "Linear Inequalities", "slug": "linear-inequalities", "class_num": 11},
    {
        "name": "Permutations and Combinations",
        "slug": "permutations-combinations",
        "class_num": 11,
    },
    {"name": "Binomial Theorem", "slug": "binomial-theorem", "class_num": 11},
    {"name": "Sequences and Series", "slug": "sequences-series", "class_num": 11},
    {"name": "Straight Lines", "slug": "straight-lines", "class_num": 11},
    {"name": "Conic Sections", "slug": "conic-sections", "class_num": 11},
    {"name": "Limits and Derivatives", "slug": "limits-derivatives", "class_num": 11},
    # Class 12
    {
        "name": "Relations and Functions (12)",
        "slug": "relations-functions-12",
        "class_num": 12,
    },
    {
        "name": "Inverse Trigonometric Functions",
        "slug": "inverse-trig",
        "class_num": 12,
    },
    {"name": "Matrices", "slug": "matrices", "class_num": 12},
    {"name": "Determinants", "slug": "determinants", "class_num": 12},
    {
        "name": "Continuity and Differentiability",
        "slug": "continuity-differentiability",
        "class_num": 12,
    },
    {
        "name": "Applications of Derivatives",
        "slug": "applications-derivatives",
        "class_num": 12,
    },
    {"name": "Integrals", "slug": "integrals", "class_num": 12},
    {
        "name": "Applications of Integrals",
        "slug": "applications-integrals",
        "class_num": 12,
    },
    {
        "name": "Differential Equations",
        "slug": "differential-equations",
        "class_num": 12,
    },
    {"name": "Vector Algebra", "slug": "vector-algebra", "class_num": 12},
    {"name": "Three Dimensional Geometry", "slug": "3d-geometry", "class_num": 12},
    {"name": "Linear Programming", "slug": "linear-programming", "class_num": 12},
    {"name": "Probability (12)", "slug": "probability-12", "class_num": 12},
]

CHAPTER_MAP = {c["slug"]: c for c in CHAPTERS}
CHAPTER_BY_SLUG = CHAPTER_MAP
